spring:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    test-connection: true
    properties:
      mail.smtp.localhost: ${MAIL_HELO:localhost}
      mail.from: ${MAIL_FROM:smtp@example.com}
      mail.reply.to: ${MAIL_REPLY_TO:no-reply@example.com}

bot:
  smtp:
    username: ${BOT_SMTP_USERNAME}
    token: ${BOT_SMTP_TOKEN}
    chat-id: ${BOT_SMTP_CHAT_ID}
    to: ${BOT_SMTP_TO}
    mime-subject: ${BOT_SMTP_MIME_SUBJECT}
