spring:
  main:
    banner-mode: off

  profiles:
    active:
      - smtp_auth
      - smtp_tls

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    test-connection: true
    properties:
      mail.smtp.localhost: ${MAIL_HELO:localhost}
      mail.from: ${MAIL_FROM:smtp@example.com}
      mail.reply.to: ${MAIL_REPLY_TO:}

tg2smtp:
  subject: ${TG2SMTP_MAIL_SUBJECT}
  to: ${TG2SMTP_MAIL_TO}
  chat-id: ${TG2SMTP_CHAT_ID}
  bot:
    username: ${TG2SMTP_BOT_USERNAME}
    token: ${TG2SMTP_BOT_TOKEN}
