name: Build, Upload and Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      HAS_WEBHOOK: ${{ secrets.DEPLOYMENT_CALLBACK_URL != '' }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Upload Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=kchwr/tg2smtp:latest
          cache-to: type=inline

      - name: Call Deployment Webhook
        if: ${{ env.HAS_WEBHOOK == 'true' }}
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.DEPLOYMENT_CALLBACK_URL }}
