name: Java CI with Maven

on:
  push:
    branches: [ 'feature/*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile sources
        run: mvn -B compile test-compile
      - name: Run Unit Tests
        run: mvn -B -Ptests-unit test
      - name: Package artifact
        run: mvn -B -fae -DskipTests=true package

      - name: Report Surefire results
        uses: ScaCap/action-surefire-report@v1
